### ISSUE TITLE
Can't Deploy

### ISSUE THREAD

**Issue by NewtonJr4108** [hvuhsg/yoyocoin#21]
Hello. 
When trying to deploy the app, I followed the directions and used the docker-compose up -d
command. However, I got this error:

ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

Am I doing something wrong, or is this a bug?

**Comment by hvuhsg** [comment]
I need to check this out, I do not know what is wrong.
Is docker installed on your machine? 

Try docker-compose down
and docker-compose up (without -d)

and please share the output

**Comment by NewtonJr4108** [comment]
I have docker on my computer, but is docker-compose different?
Were you able to get it running on your computer?

**Comment by hvuhsg** [comment]
> 
> 
> I have docker on my computer, but is docker-compose different?
> Were you able to get it running on your computer?

**Comment by hvuhsg** [comment]
> 
> 
> I have docker on my computer, but is docker-compose different?
> Were you able to get it running on your computer?

Check out my last comment (Edited)

**Comment by NewtonJr4108** [comment]
Here's what happened when I did docker-compose down -d:

Stops containers and removes containers, networks, volumes, and images
created by `up`.

By default, the only things removed are:

- Containers for services defined in the Compose file
- Networks defined in the `networks` section of the Compose file
- The default network, if one is used

Networks and volumes defined as `external` are never removed.

Usage: down [options]

Options:
    --rmi type              Remove images. Type must be one of:
                              'all': Remove all images used by any service.
                              'local': Remove only images that don't have a
                              custom tag set by the `image` field.
    -v, --volumes           Remove named volumes declared in the `volumes`
                            section of the Compose file and anonymous volumes
                            attached to containers.
    --remove-orphans        Remove containers for services not defined in the
                            Compose file
    -t, --timeout TIMEOUT   Specify a shutdown timeout in seconds.
                            (default: 10)

It just listed what it does.

When I did it without the -d, it just listed the original up -d output.

**Comment by hvuhsg** [comment]
docker-compose down (without -d)

**Comment by hvuhsg** [comment]
https://techoverflow.net/2019/03/16/how-to-fix-error-couldnt-connect-to-docker-daemon-at-httpdocker-localhost-is-it-running/

Solution:

There are two possible reasons for this error message.

The common reason is that the user you are running the command as does not have the permissions to access docker.

You can fix this either by running the command as root using sudo (since root has the permission to access docker) or adding your user to the docker group:
`sudo usermod -a -G docker $USER`

and then logging out and logging back in completely (or restarting the system/server).

The other reason is that you have not started docker. On Ubuntu, you can start it using
```
sudo systemctl enable docker # Auto-start on boot
sudo systemctl start docker # Start right now
```

**Comment by NewtonJr4108** [comment]
Thanks. I’ll look into both solutions  and get back to you with results.

**Comment by NewtonJr4108** [comment]
I tried using sudo in the command, and also started docker on the system, as well as adding my user to my docker group, but got the same result.
Tell me the exact steps you did to get the program up and running.

**Comment by hvuhsg** [comment]
This issue does not related to this repo, so I am closing it.
