### ISSUE TITLE
How do you get it to work exactly?

### ISSUE THREAD

**Issue by NewtonJr4108** [hvuhsg/yoyocoin#5]
Hello. There are a lot of bugs in this project(specifically import errors), but its very interesting. How exactly do you make it run so you can stake coins and stuff?

**Comment by cuDNN-error** [comment]
True, there is no way of opening but perhaps python app.py might work but considering the amount of bugs it most likely would not.

**Comment by hvuhsg** [comment]
Hi the code is not working yet (in-progress)
The consensus will use aspects of PoS but with my own twist
there is no validators or stake
every wallet that hold some amount of coins have a chance of winning the "lottery" and creating the next block the chance is calculated 100 - (wallet.balance / wallet.last_transaction[block index])

more coins = more chance to win
AND
wallet last transaction lower = more chance to win

if the winner is not online the closest wallet address is winning and so on

the import errors are for development-env reason
